### ISSUE TITLE
EEPROM library need update

### ISSUE THREAD

**Issue by ricardojlrufino** [energia/tivac-core#13]
This version is very old, and is missing some methods:
How to: get, put, length

See:
https://www.arduino.cc/en/Reference/EEPROM
https://github.com/arduino/Arduino/blob/master/hardware/arduino/avr/libraries/EEPROM/src/EEPROM.h

You must upgrade to maintain compatibility

**Comment by robertinant** [comment]
Thanks for the report. If you already have something in the works then it would be great if you could submit a pull request.

**Comment by ricardojlrufino** [comment]
Sorry, but i don't have

**Comment by robertinant** [comment]
Addressed in 1.0.4.
The EEPROM library was replaced with the 2.0.0 version of Arduino avr
https://github.com/energia/tivac-core/commit/95a86a036fa138f32ae9ce9129975125c85afae1
