### ISSUE TITLE
Compiler not found for TivaC package - Linux64

### ISSUE THREAD

**Issue by rei-vilo** [energia/tivac-core#14]
See https://github.com/energia/Energia/issues/939

**Comment by ghost** [comment]
I encountered same problem, with Ubuntu 16.04 LTS.  The solution is:

dpkg --add-architecture i386
apt-get update
apt-get install libc6:i386 libstdc++6:i386

**Comment by robertinant** [comment]
For some reason the wrong compiler was packaged for Linux 64-bit. I will correct this in a package update.
