### ISSUE TITLE
Ethernet library includes code which "may not combine with viral open-source"

### ISSUE THREAD

**Issue by jonnor** [energia/tivac-core#19]
For example in [lwiplib.c](https://github.com/energia/tivac-core/blob/964881c/libraries/Ethernet/utility/lwiplib.c)
```
// Texas Instruments (TI) is supplying this software for use solely and
// exclusively on TI's microcontroller products. The software is owned by
// TI and/or its suppliers, and is protected under applicable copyright
// laws. You may not combine this software with "viral" open-source
// software in order to form a larger program.
```

Energia is LGPL, which I guess someone could argue is "viral".

And even regardless of this, this license does not seem very friendly for use in a third party product (be it open source or not).

**Comment by jonnor** [comment]
Can this be clarified/fixed by copyright holder (TI)?

Or are there alternative implementations that can replace this?

**Comment by robertinant** [comment]
Thanks for the report! 
Working on getting this converted to BSD 3 with the folks over at TI.

**Comment by jonnor** [comment]
Hi again. Was there any progress made on getting an open source license on this?

**Comment by robertinant** [comment]
Unfortunately the initial answer from the TivaC group over at TI was no. I will keep trying to get this converted.
