### ISSUE TITLE
Boards tags

### ISSUE THREAD

**Issue by rei-vilo** [energia/tivac-core#3]
If the boards names are used as boards tag as for the MSP430, then the TM4C-based boards should be 

| Current tag | Suggested tag |
| --- | --- |
| lplm4f120h5qr | EK-LM4F120XL |
| lptm4c1230c3pm | EK-TM4C123GXL |
| lptm4c1294ncpdt | EK-TM4C1294XL |

**Comment by robertinant** [comment]
Fixed with 0ef297d224b992d1298b5aabfd89b34ee6dfb4b9
