### ISSUE TITLE
Release 1.0.3 Not Available on Boards Manager 

### ISSUE THREAD

**Issue by rei-vilo** [energia/tivac-core#37]
The release 1.0.3 isn't available for download on the Boards Manager.

<img width="800" alt="capture 2017-09-01 a 19 31 18" src="https://user-images.githubusercontent.com/951776/29980952-28aaaff4-8f4c-11e7-8422-9e681794a4cf.png">

**Comment by robertinant** [comment]
It should be. If you select it it shows displays an "update" button which will update it to 1.0.3.
