### ISSUE TITLE
Illegal Characters in Boards Tags

### ISSUE THREAD

**Issue by rei-vilo** [energia/tivac-core#4]
Compiler complains about an illegal character on the board tags for Tiva C boards. 

Pre-processing statements based on the board-tag fail to compile because of the `-`. Use `_` instead.
- Error message

> "/Users/ReiVilo/Library/Energia15/packages/energia/tools/arm-none-eabi-gcc/4.8.4-20140725/bin/arm-none-eabi-g++" -c -g -Os -w -std=gnu++11 -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -Dprintf=iprintf  -w -x c++ -E -CC -mcpu=cortex-m4 -mthumb -DF_CPU=80000000L -DARDUINO=10610 -DENERGIA=10610 -DENERGIA_EK-TM4C123GXL -DENERGIA_ARCH_TIVAC "-I/Users/ReiVilo/Library/Energia15/packages/energia/hardware/tivac/1.0.2/variants/EK-TM4C123GXL" "-I/Users/ReiVilo/Library/Energia15/packages/energia/hardware/tivac/1.0.2/system/driverlib" "-I/Users/ReiVilo/Library/Energia15/packages/energia/hardware/tivac/1.0.2/system/inc" "-I/Users/ReiVilo/Library/Energia15/packages/energia/hardware/tivac/1.0.2/system" -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mabi=aapcs "-I/Users/ReiVilo/Library/Energia15/packages/energia/hardware/tivac/1.0.2/cores/tivac" "-I/Users/ReiVilo/Library/Energia15/packages/energia/hardware/tivac/1.0.2/variants/EK-TM4C123GXL" "/var/folders/hz/wncgspfd5wxgzmly78yvzk_m0000gn/T/buildab8afa78f9a8f0d7cde72ceba978da5e.tmp/sketch/sketch_jun29a.ino.cpp" -o "/dev/null"
- Code

```
#if defined(ENERGIA_EK-TM4C123GXL)
#warning ENERGIA_EK-TM4C123GXL
#endif

void setup() {
  // put your setup code here, to run once:

}

void loop() {
  // put your main code here, to run repeatedly: 

}
```
- Solution

`ENERGIA_EK-TM4C123GXL` should be `ENERGIA_EK_TM4C123GXL`
`ENERGIA_EK-TM4C1294XL` should be `ENERGIA_EK_ TM4C1294XL`

**Comment by robertinant** [comment]
Fixed with fdf55824d781794d66337f04a2daec6cb529f657
