### ISSUE TITLE
TivaC serial port does not show up on macOS catalina

### ISSUE THREAD

**Issue by robertinant** [energia/tivac-core#44]
https://forum.43oh.com/topic/13584-problem-with-serial-connection-on-mac-os-catalina/

**Comment by rei-vilo** [comment]
No problem on my side with macOS 10.15.1 _Catalina_.

Plugging-in a TM4C123G LaunchPad and launching `ls /dev/tty.*` list the serial port `/dev/tty.usbmodem0E2016EB1`.

```
% ls /dev/tty.*
/dev/tty.Bluetooth-Incoming-Port	/dev/tty.usbmodem0E2016EB1
```

Similarly, both uploading with **DSLite**...


```
/Users/ReiVilo/Library/Energia15/packages/energia/tools/dslite/7.2.0.2096/DebugServer/bin/DSLite load -c /Users/ReiVilo/Library/Energia15/packages/energia/tools/dslite/7.2.0.2096/EK-TM4C123GXL.ccxml -f /Users/ReiVilo/Library/Developer/Xcode/DerivedData/embed1-fykzaoosymfojzbkmxucgqqixhyu/Build/Products/Debug/embeddedcomputing.elf`
```

...and using `screen` for serial console...

```
% screen /dev/tty.usbmodem0E2016EB1 9600
```

...work fine on my side.

**Comment by robertinant** [comment]
@cenkaybiyik

I don't see any issues either so this is not a bug. Can you please post a question in the forum here: https://forum.43oh.com/forum/125-energia-tivaccc3xxx/ so that we can follow up there:
