### ISSUE TITLE
version of TivaWare

### ISSUE THREAD

**Issue by RickKimball** [energia/tivac-core#7]
Is there a reason you haven't moved to the latest version of TivaWare?

**Comment by robertinant** [comment]
No technical reason. It's on the list but I have not had the time to get to it..

**Comment by RickKimball** [comment]
I gave it a try and it exposed an issue with ROM_GPIOPadConfigSet for the tm4c1294 boards.

**Comment by robertinant** [comment]
I have upgraded driverlib to the latest version. Commit will follow soon.
