### ISSUE TITLE
Compiler warnings because of board naming. 

### ISSUE THREAD

**Issue by RickKimball** [energia/tivac-core#9]
Same issue I reported on the msp430 packages. https://github.com/robertinant/EnergiaNG/issues/10 
https://github.com/energia/tivac-core/blob/master/boards.txt#L7

You might want to check all the boards.txt files for all the cores?

I found this when I downloaded and installed the distribution from:

http://energia.nu/downloads/downloadv4.php?file=energia-1.6.10E18-linux64.tar.xz

**Comment by robertinant** [comment]
fixed
